# See readme for how to generate and maintain this list
jenkins:
  controller:
    installLatestPlugins: false
    installPlugins:
      - "analysis-model-api:11.7.1"
      - "antisamy-markup-formatter:162.v0e6ec0fcfcf6"
      - "apache-httpcomponents-client-4-api:4.5.14-208.v438351942757"
      - "authentication-tokens:1.53.v1c90fd9191a_b_"
      - "basic-branch-build-strategies:81.v05e333931c7d"
      - "bootstrap5-api:5.3.0-1"
      - "bouncycastle-api:2.29"
      - "branch-api:2.1128.v717130d4f816"
      - "caffeine-api:3.1.8-133.v17b_1ff2e0599"
      - "checks-api:2.0.1"
      - "cloudbees-folder:6.848.ve3b_fd7839a_81"
      - "command-launcher:107.v773860566e2e"
      - "commons-lang3-api:3.13.0-62.v7d18e55f51e2"
      - "commons-text-api:1.10.0-78.v3e7b_ea_d5a_fe1"
      - "configuration-as-code:1700.v6f448841296e"
      - "copyartifact:722.v0662a_9b_e22a_c"
      - "credentials-binding:636.v55f1275c7b_27"
      - "credentials:1271.v54b_1c2c6388a_"
      - "data-tables-api:1.13.5-1"
      - "discord-notifier:241.v448b_ccd0c0d6"
      - "display-url-api:2.3.9"
      - "durable-task:523.va_a_22cf15d5e0"
      - "echarts-api:5.4.0-5"
      - "extra-columns:1.26"
      - "font-awesome-api:6.4.0-2"
      - "forensics-api:2.3.0"
      - "git-client:4.5.0"
      - "git-forensics:2.0.0"
      - "git:5.2.0"
      - "github-api:1.314-431.v78d72a_3fe4c3"
      - "github-branch-source:1740.v51d5810e9e8c"
      - "github-checks:554.vb_ee03a_000f65"
      - "github-oauth:588.vf696a_350572a_"
      - "github:1.37.3"
      - "groovy:453.vcdb_a_c5c99890"
      - "htmlpublisher:1.32"
      - "http_request:1.18"
      - "instance-identity:173.va_37c494ec4e5"
      - "ionicons-api:56.v1b_1c8c49374e"
      - "jackson2-api:2.15.2-350.v0c2f3f8fc595"
      - "jakarta-activation-api:2.0.1-3"
      - "jakarta-mail-api:2.0.1-3"
      - "javadoc:243.vb_b_503b_b_45537"
      - "javax-activation-api:1.2.0-6"
      - "javax-mail-api:1.6.2-9"
      - "jaxb:2.3.8-1"
      - "jdk-tool:73.vddf737284550"
      - "jjwt-api:0.11.5-77.v646c772fddb_0"
      - "job-dsl:1.85"
      - "jquery3-api:3.7.0-1"
      - "junit:1217.v4297208a_a_b_ce"
      - "kubernetes-cli:1.12.1"
      - "kubernetes-client-api:6.8.1-224.vd388fca_4db_3b_"
      - "kubernetes-credentials:0.11"
      - "kubernetes:4029.v5712230ccb_f8"
      - "label-linked-jobs:6.0.1"
      - "mailer:463.vedf8358e006b_"
      - "matrix-project:808.v5a_b_5f56d6966"
      - "metrics:4.2.18-442.v02e107157925"
      - "mina-sshd-api-common:2.10.0-69.v28e3e36d18eb_"
      - "mina-sshd-api-core:2.10.0-69.v28e3e36d18eb_"
      - "okhttp-api:4.11.0-157.v6852a_a_fa_ec11"
      - "permissive-script-security:0.7"
      - "pipeline-build-step:505.v5f0844d8d126"
      - "pipeline-gitstatuswrapper:1.2.0"
      - "pipeline-graph-analysis:202.va_d268e64deb_3"
      - "pipeline-groovy-lib:689.veec561a_dee13"
      - "pipeline-input-step:477.v339683a_8d55e"
      - "pipeline-model-api:2.2144.v077a_d1928a_40"
      - "pipeline-model-definition:2.2144.v077a_d1928a_40"
      - "pipeline-model-extensions:2.2144.v077a_d1928a_40"
      - "pipeline-rest-api:2.33"
      - "pipeline-stage-step:305.ve96d0205c1c6"
      - "pipeline-stage-tags-metadata:2.2144.v077a_d1928a_40"
      - "pipeline-stage-view:2.33"
      - "pipeline-utility-steps:2.16.0"
      - "plain-credentials:143.v1b_df8b_d3b_e48"
      - "plugin-util-api:3.3.0"
      - "prism-api:1.29.0-8"
      - "scm-api:676.v886669a_199a_a_"
      - "script-security:1275.v23895f409fb_d"
      - "snakeyaml-api:2.2-111.vc6598e30cc65"
      - "ssh-credentials:308.ve4497b_ccd8f4"
      - "sshd:3.312.v1c601b_c83b_0e"
      - "structs:325.vcb_307d2a_2782"
      - "templating-engine:2.5.3"
      - "thinBackup:1.18"
      - "token-macro:384.vf35b_f26814ec"
      - "trilead-api:2.84.v72119de229b_7"
      - "variant:60.v7290fc0eb_b_cd"
      - "view-job-filters:369.ve0513a_a_f5524"
      - "warnings-ng:10.4.0"
      - "workflow-api:1281.vca_5fddb_3fceb_"
      - "workflow-basic-steps:1042.ve7b_140c4a_e0c"
      - "workflow-cps:3787.v8f5dcd14a_fa_c"
      - "workflow-durable-task-step:1289.v4d3e7b_01546b_"
      - "workflow-job:1326.ve643e00e9220"
      - "workflow-multibranch:756.v891d88f2cd46"
      - "workflow-scm-step:415.v434365564324"
      - "workflow-step-api:639.v6eca_cd8c04a_a_"
      - "workflow-support:865.v43e78cc44e0d"
